"""
Django settings for geekshop project.
Generated by 'django-admin startproject' using Django 3.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

import social_core
from dotenv import load_dotenv

from geekshop.settingutils import create_env_file, get_bool_from_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


ENV_FILE = os.path.join(BASE_DIR, '.env')
if os.path.exists(ENV_FILE) and os.path.isfile(ENV_FILE):
    load_dotenv(ENV_FILE)
else:
    create_env_file(ENV_FILE)
    load_dotenv(ENV_FILE)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", '123'),

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_from_env("DEBUG", False)
# Set production for run at real server
PRODUCTION = get_bool_from_env("PRODUCTION", False)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ####### project apps ####
    "common",
    "mainapp",
    "authapp",
    "ordersapp",
    "basketapp",
    "adminapp",
    "social_django",
    "debug_toolbar",
    "template_profiler_panel",
    "django_extensions"
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'geekshop.middlware_disavle_csrf.DisableCSRFMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'geekshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'basketapp.context_processors.basket',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'geekshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'geekshop',
            'USER': 'postgres',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# media upload settings
MEDIA_ROOT_SHORT = 'media'
MEDIA_URL = f'/{MEDIA_ROOT_SHORT}/'
MEDIA_ROOT = os.path.join(BASE_DIR, f'{MEDIA_ROOT_SHORT}')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# auth for custom usermodel
AUTH_USER_MODEL = 'authapp.User'

# login redirect
LOGIN_URL = "/authapp/login"
LOGIN_REDIRECT_URL = "/"
LOGIN_ERROT_URL = '/'

# # email
# # used in email message for activation url
# DOMAIN_NAME = 'http:/mysupersite.ru'
# # real django mail settings
# EMAIL_HOST = 'mail.ru'
# EMAIL_PORT = '25'
# EMAIL_HOST_USER = 'robot@mysupersite.ru'
# EMAIL_HOST_PASSWORD = 'robot pass'
# EMAIL_USE_SSL = True
# EMAIL_TIMEOUT = 60

# ACTIVATION_KEY_EXPIRED_HOURS = 72

# вариант python -m smtpd -n -c DebuggingServer localhost:25

if PRODUCTION:
    DOMAIN_NAME = os.environ.get("DOMAIN_NAME", 'yoursitedomain.ru')
    # real django mail settings
    EMAIL_HOST = os.environ.get("EMAIL_HOST", 'smtp.domain.ru')
    EMAIL_PORT = os.environ.get("EMAIL_PORT", '25')
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", 'user@domain.ru')
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", '')
    EMAIL_USE_SSL = True
    EMAIL_TIMEOUT = 60
else:
    # email
    # used in email message
    DOMAIN_NAME = 'http://localhost:8000'
    # real django mail settings
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = '25'
    EMAIL_HOST_USER = None
    EMAIL_HOST_PASSWORD = None
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 20

# add this for log email in files
# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_FILE_PATH = 'tmp/email-messages/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.vk.VKOAuth2',
)

VK_OUATH_KEY = os.environ.get("VK_OAUTH2_KEY")
VK_OUATH_SECRET = os.environ.get("VK_OAUTH2_SECRET")

if not VK_OUATH_KEY or not VK_OUATH_SECRET:
    print("WARNING! VK OAUTH SETTINGS ARE INVALID. Check .env file")

SOCIAL_AUTH_VK_OAUTH2_KEY = VK_OUATH_KEY
SOCIAL_AUTH_VK_OAUTH2_SECRET = VK_OUATH_SECRET
SOCIAL_AUTH_VK_OAUTH2_API_VERSION = '5.131'
SOCIAL_AUTH_VK_OAUTH2_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.create_user',
    'authapp.pipelines.save_user_profile',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

if DEBUG:
    def show_toolbar(request):
        return True


    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': show_toolbar,
    }

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
        'template_profiler_panel.panels.template.TemplateProfilerPanel',
    ]

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = os.environ.get("CACHE_MIDDLEWARE_SECONDS", '120')
CACHE_MIDDLEWARE_KEY_PREFIX = os.environ.get("CACHE_MIDDLEWARE_KEY_PREFIX", 'geekshop')
LOW_CACHE = get_bool_from_env('LOW_CACHE', True)

MEMCACHE_SERVER = os.environ.get("MEMCACHE_SERVER", '127.0.0.1')
MEMCACHE_PORT = os.environ.get("MEMCACHE_SERVER", '11211')
MEMCACHE_CONNECTION = f"{MEMCACHE_SERVER}:{MEMCACHE_PORT}"
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': MEMCACHE_CONNECTION,
    }
}
pass
