# Generated by Django 3.2.6 on 2022-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_avatar'),
        ),
    ]
