# Generated by Django 3.2.6 on 2022-04-26 19:53

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0004_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expire',
            field=models.DateTimeField(blank=True,
                                       default=datetime.datetime(2022, 4, 29, 19, 53, 1, 883886, tzinfo=utc),
                                       null=True),
        ),
    ]
