# Generated by Django 3.2.6 on 2022-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=5, verbose_name='Язык'),
        ),
    ]
