# Generated by Django 3.2.6 on 2022-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=25, verbose_name='Язык'),
        ),
    ]
