# Generated by Django 3.2.6 on 2022-05-04 15:10

from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0013_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=authapp.models.upload_avatar),
        ),
    ]
